title: Empty Page Deleter
description: This Add-On detects pages with no text in a document and gives you the option of deleting them/
type: object
documents:
  - selected
properties: {}
categories: 
  - file
# Acceptable categories are premium, ai, export, bulk, file,  monitor, statistical, and extraction. 
# You can read more about DocumentCloud Add-On categories here: https://www.documentcloud.org/help/add-ons#types-of-add-ons
