title: Empty Page Deleter
description: This Add-On detects pages with no text in a document, deletes the pages, and re-uploads the document with those pages removed. 
type: object
documents:
  - selected
  - query
properties: 
  project_id:
     title: Project ID of the project you would like the documents uploaded to (optional)
     type: integer
required:
  - project_id
categories: 
  - file
# Acceptable categories are premium, ai, export, bulk, file,  monitor, statistical, and extraction. 
# You can read more about DocumentCloud Add-On categories here: https://www.documentcloud.org/help/add-ons#types-of-add-ons
